var dataIN = [{"id":"Household","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept"},
{"id":"State","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept"},
{"id":"Indentity","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept"},
{"id":"Demographics","group":"Proxies","level":2,"discipline":"arch","Type":"concept"},
{"id":"Health","group":"Proxies","level":2,"discipline":"arch","Type":"concept"},
{"id":"Technology","group":"Technology","level":2,"discipline":"arch","Type":"concept"},
{"id":"Infrastructure (Urban)","group":"Technology","level":2,"discipline":"arch","Type":"concept"},
{"id":"Ideology","group":"Drivers","level":2,"discipline":"arch","Type":"concept"},
{"id":"Succesion","group":"Consequence","level":2,"discipline":"eco","Type":"concept"},
{"id":"Adaptation Ability","group":"Consequence","level":2,"discipline":"eco","Type":"concept"},
{"id":"Forest Cover","group":"Consequence","level":2,"discipline":"eco","Type":"concept"},
{"id":"Biodiversity","group":"Consequence","level":2,"discipline":"eco","Type":"concept"},
{"id":"Agriculture and Grazing","group":"Drivers","level":2,"discipline":"eco","Type":"concept"},
{"id":"Population Count","group":"Synthesis","level":2,"discipline":"eco; arch","Type":"concept"},
{"id":"Society ","group":"","level":4,"discipline":"eco; arch","Type":"concept"},
{"id":"Motion / Travel / Connectivity","group":"","level":"","discipline":"eco; hgeo","Type":"concept"},
{"id":"Resilience","group":"Synthesis","level":2,"discipline":"eco; hgeo","Type":"concept"},
{"id":"Land Use","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept"},
{"id":"Meaning / Values","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept"},
{"id":"Power Relations","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept"},
{"id":"Social Structure","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept"},
{"id":"Community","group":"Materiality","level":2,"discipline":"hgeo","Type":"concept"},
{"id":"Diversity","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept"},
{"id":"Traditions","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo; arch","Type":"concept"},
{"id":"Practises / Activities","group":"Politics and Governance","level":3,"discipline":"hgeo; arch","Type":"concept"},
{"id":"Institutions","group":"Social Dimensions","level":2,"discipline":"hgeo; arch","Type":"concept"},
{"id":"Pottery Sherds (fabric)","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Coins","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Architectural Buidlings","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Fauna / Flora ( observations )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"aDNA","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Survey in Valley systems (Archeological)","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Soil color & texture (excavation)","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Material Waste","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Communal Dinning ( Site )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Skeletons","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Remote Sensing of Valey Systems","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Landscape Characteristics (eg. elevation, access etc)","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Land Use in Valley Systems","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Rewildered  trees eg fruit ( observation )","group":"","level":2,"discipline":"eco","Type":"data"},
{"id":"Pollen","group":"","level":2,"discipline":"eco","Type":"data"},
{"id":"Trends Long Term","group":"","level":2,"discipline":"eco","Type":"data"},
{"id":"Climate Modeling (6000 years)","group":"","level":2,"discipline":"eco","Type":"data"},
{"id":"Temperature & Precipitation ( 500 years)","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Tree and plant type ( Observation )","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Phosporus Levels in Soil ","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Soil Erosion (10000 years)","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Forest Biomass ( 4000 years )","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Maps (Historical , Sattelite Images )","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"Oral Histories ( interviews)","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"Mapping (Actor and Institutional )","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"State Registers","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"Meta-analysis of Sources","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"Conceptual Maps","group":"","level":3,"discipline":"hgeo","Type":"data"},
{"id":"Local Narratives","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Household Interviews","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Sketches ( ethnographic )","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Location of Water Sources","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Written Regulations","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Irrigation Channels","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Household Surveys","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Survey Photographs","group":"","level":"","discipline":"hgeo","Type":"data"},
{"id":"Unevenly Grown bushes (Observation): grazing indicator","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Degradation Indicators, tree types: Juniper","group":"","level":"","discipline":"eco","Type":"data"},
{"id":"Worked Stone ( Observation )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Pottery Sherds ( templates )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Human Bones","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Animal Bones","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Graves ( Sites )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Architectural Notebooks ( operational: reconstruction, credibility )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"C and O isotope analysis ( Dating )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Survey Notebooks ( operational: credibility )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Excavation Notebooks ( operational: credibility )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Excavation Layer Photographs ( operational)","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Pottery Sherds ( Illustrations )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Pottery Sherds ( photographs )","group":"","level":"","discipline":"arch","Type":"data"},
{"id":"Landscape Characteristics (eg. viewshed, outpost, elevation )","group":"","level":"","discipline":"arch","Type":"data"}];