var dataIN = [{"id":"Social","group":"","level":1,"discipline":"eco; arch","Type":"concept","pos_x":8,"pos_y":4},
{"id":"Household","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":8,"pos_y":2},
{"id":"State","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":4},
{"id":"Indentity","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":8,"pos_y":3},
{"id":"Demographics","group":"Proxies","level":2,"discipline":"arch","Type":"concept","pos_x":9,"pos_y":3},
{"id":"Technology","group":"Technology","level":1,"discipline":"arch","Type":"concept","pos_x":5,"pos_y":2},
{"id":"Urban Infrastructure","group":"Technology","level":2,"discipline":"arch","Type":"concept","pos_x":6,"pos_y":2},
{"id":"Slow Technologies","group":"Technology","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":2},
{"id":"Spatial","group":"Spatial","level":1,"discipline":"arch","Type":"concept","pos_x":6,"pos_y":3},
{"id":"Definition of Region","group":"Spatial","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":3},
{"id":"Population Count","group":"Synthesis","level":2,"discipline":"eco; arch","Type":"concept","pos_x":8,"pos_y":6},
{"id":"Succesion","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":4,"pos_y":6},
{"id":"Adaptation Ability","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":5,"pos_y":6},
{"id":"Forest Cover","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":5,"pos_y":7},
{"id":"Biodiversity","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":4,"pos_y":5},
{"id":"Agriculture and Grazing","group":"Drivers","level":2,"discipline":"eco","Type":"concept","pos_x":6,"pos_y":6},
{"id":"Motion - Travel - Connectivity","group":"","level":"","discipline":"hgeo; arch; eco","Type":"concept","pos_x":6,"pos_y":4},
{"id":"Resilience - Resources through time","group":"Synthesis","level":2,"discipline":"eco; hgeo","Type":"concept","pos_x":5,"pos_y":5},
{"id":"Nature-Culture Interactions","group":"","level":1,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":5},
{"id":"Land Use","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":6},
{"id":"Meaning / Values","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":3},
{"id":"Traditions","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo; arch","Type":"concept","pos_x":2,"pos_y":4},
{"id":"Practises / Activities","group":"Politics and Governance","level":3,"discipline":"hgeo; arch","Type":"concept","pos_x":5,"pos_y":1},
{"id":"Politics and Governance","group":"","level":1,"discipline":"hgeo","Type":"concept","pos_x":3,"pos_y":3},
{"id":"Institutions","group":"Social Dimensions","level":2,"discipline":"hgeo; arch","Type":"concept","pos_x":1,"pos_y":3},
{"id":"Power Structures & Relations","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept","pos_x":3,"pos_y":2},
{"id":"Social Structure & Relations ","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept","pos_x":4,"pos_y":3},
{"id":"Community","group":"Materiality","level":2,"discipline":"hgeo","Type":"concept","pos_x":8,"pos_y":5},
{"id":"Pottery Sherds (fabric)","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Coins","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Architectural Buidlings","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Fauna / Flora ( observations )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"aDNA","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Survey in Valley systems (Archeological)","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Soil color & texture (excavation)","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Material Waste","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Communal Dinning ( Site )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Skeletons","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Remote Sensing of Valey Systems","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Landscape Characteristics (eg. elevation, access etc)","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Land Use in Valley Systems","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Rewildered  trees eg fruit ( observation )","group":"","level":2,"discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Pollen","group":"","level":2,"discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Trends Long Term","group":"","level":2,"discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Climate Modeling (6000 years)","group":"","level":2,"discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Temperature & Precipitation ( 500 years)","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Tree and plant type ( Observation )","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Phosporus Levels in Soil ","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Soil Erosion (10000 years)","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Forest Biomass ( 4000 years )","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Maps (Historical , Sattelite Images )","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Oral Histories ( interviews)","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Mapping (Actor and Institutional )","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"State Registers","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Meta-analysis of Sources","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Conceptual Maps","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Local Narratives","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Household Interviews","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Sketches ( ethnographic )","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Location of Water Sources","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Written Regulations","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Irrigation Channels","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Household Surveys","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Survey Photographs","group":"","level":"","discipline":"hgeo","Type":"data","pos_x":"","pos_y":""},
{"id":"Unevenly Grown bushes (Observation): grazing indicator","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Degradation Indicators, tree types: Juniper","group":"","level":"","discipline":"eco","Type":"data","pos_x":"","pos_y":""},
{"id":"Worked Stone ( Observation )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Pottery Sherds ( templates )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Human Bones","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Animal Bones","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Graves ( Sites )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Architectural Notebooks ( operational: reconstruction, credibility )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"C and O isotope analysis ( Dating )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Survey Notebooks ( operational: credibility )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Excavation Notebooks ( operational: credibility )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Excavation Layer Photographs ( operational)","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Pottery Sherds ( Illustrations )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Pottery Sherds ( photographs )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""},
{"id":"Landscape Characteristics (eg. viewshed, outpost, elevation )","group":"","level":"","discipline":"arch","Type":"data","pos_x":"","pos_y":""}]