var dataIN = [{"id":"Social","Label":"Social","group":"","level":1,"discipline":"eco; arch","Type":"concept","pos_x":8,"pos_y":4,"oblig":"FALSE"},
{"id":"Household","Label":"Household","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":8,"pos_y":2,"oblig":"FALSE"},
{"id":"State","Label":"State","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":4,"oblig":"FALSE"},
{"id":"Indentity","Label":"Indentity","group":"Social Dimensions","level":2,"discipline":"arch","Type":"concept","pos_x":8,"pos_y":3,"oblig":"FALSE"},
{"id":"Demographics","Label":"Demographics","group":"Proxies","level":2,"discipline":"arch","Type":"concept","pos_x":9,"pos_y":3,"oblig":"TRUE"},
{"id":"Technology","Label":"Technology","group":"Technology","level":1,"discipline":"arch","Type":"concept","pos_x":5,"pos_y":2,"oblig":"FALSE"},
{"id":"Urban Infrastructure","Label":"Urban Infrastructure","group":"Technology","level":2,"discipline":"arch","Type":"concept","pos_x":6,"pos_y":2,"oblig":"FALSE"},
{"id":"Slow Technologies","Label":"Slow Technologies","group":"Technology","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":2,"oblig":"FALSE"},
{"id":"Spatial","Label":"Spatial","group":"Spatial","level":1,"discipline":"arch","Type":"concept","pos_x":6,"pos_y":3,"oblig":"FALSE"},
{"id":"Definition of Region","Label":"Definition of Region","group":"Spatial","level":2,"discipline":"arch","Type":"concept","pos_x":7,"pos_y":3,"oblig":"FALSE"},
{"id":"Population Count","Label":"Population Count","group":"Synthesis","level":2,"discipline":"eco; arch","Type":"concept","pos_x":8,"pos_y":6,"oblig":"TRUE"},
{"id":"Succesion","Label":"Succesion","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":4,"pos_y":6,"oblig":"FALSE"},
{"id":"Adaptation Ability","Label":"Adaptation Ability","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":5,"pos_y":6,"oblig":"FALSE"},
{"id":"Forest Cover","Label":"Forest Cover","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":5,"pos_y":7,"oblig":"TRUE"},
{"id":"Biodiversity","Label":"Biodiversity","group":"Consequence","level":2,"discipline":"eco","Type":"concept","pos_x":4,"pos_y":5,"oblig":"FALSE"},
{"id":"Agriculture and Grazing","Label":"Agriculture and Grazing","group":"Drivers","level":2,"discipline":"eco","Type":"concept","pos_x":6,"pos_y":6,"oblig":"FALSE"},
{"id":"Motion - Travel - Connectivity","Label":"Motion - Travel - Connectivity","group":"","level":2,"discipline":"hgeo; arch; eco","Type":"concept","pos_x":6,"pos_y":4,"oblig":"FALSE"},
{"id":"Resilience - Resources through time","Label":"Resilience - Resources through time","group":"Synthesis","level":2,"discipline":"eco; hgeo","Type":"concept","pos_x":5,"pos_y":5,"oblig":"FALSE"},
{"id":"Nature-Culture Interactions","Label":"Nature-Culture Interactions","group":"","level":1,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":5,"oblig":"FALSE"},
{"id":"Land Use","Label":"Land Use","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":6,"oblig":"TRUE"},
{"id":"Meaning / Values","Label":"Meaning / Values","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo","Type":"concept","pos_x":2,"pos_y":3,"oblig":"FALSE"},
{"id":"Traditions","Label":"Traditions","group":"Nature-Culture Interactions","level":3,"discipline":"hgeo; arch","Type":"concept","pos_x":2,"pos_y":4,"oblig":"FALSE"},
{"id":"Practises / Activities","Label":"Practises / Activities","group":"Politics and Governance","level":3,"discipline":"hgeo; arch","Type":"concept","pos_x":5,"pos_y":1,"oblig":"TRUE"},
{"id":"Politics and Governance","Label":"Politics and Governance","group":"","level":1,"discipline":"hgeo","Type":"concept","pos_x":3,"pos_y":3,"oblig":"FALSE"},
{"id":"Institutions","Label":"Institutions","group":"Social Dimensions","level":2,"discipline":"hgeo; arch","Type":"concept","pos_x":1,"pos_y":3,"oblig":"TRUE"},
{"id":"Power Structures & Relations","Label":"Power Structures & Relations","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept","pos_x":3,"pos_y":2,"oblig":"FALSE"},
{"id":"Social Structure & Relations ","Label":"Social Structure & Relations ","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"concept","pos_x":4,"pos_y":3,"oblig":"FALSE"},
{"id":"Community","Label":"Community","group":"Materiality","level":2,"discipline":"hgeo","Type":"concept","pos_x":8,"pos_y":5,"oblig":"FALSE"},
{"id":"Pottery Sherds (fabric)","Label":"Pottery Sherds (fabric)","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Coins","Label":"Coins","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Architectural Buidlings","Label":"Architectural Buidlings","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Fauna / Flora ( observations )","Label":"Fauna / Flora ( observations )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"aDNA","Label":"aDNA","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Survey in Valley systems (Archeological)","Label":"Survey in Valley systems (Archeological)","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Soil color & texture (excavation)","Label":"Soil color & texture (excavation)","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Material Waste","Label":"Material Waste","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Communal Dinning ( Site )","Label":"Communal Dinning ( Site )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Skeletons","Label":"Skeletons","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Remote Sensing of Valey Systems","Label":"Remote Sensing of Valey Systems","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Landscape Characteristics (eg. elevation, access etc)","Label":"Landscape Characteristics (eg. elevation, access etc)","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Land Use in Valley Systems","Label":"Land Use in Valley Systems","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Rewildered  trees eg fruit ( observation )","Label":"Rewildered  trees eg fruit ( observation )","group":"","level":2,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Pollen","Label":"Pollen","group":"","level":2,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Trends Long Term","Label":"Trends Long Term","group":"","level":2,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Climate Modeling (6000 years)","Label":"Climate Modeling (6000 years)","group":"","level":2,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Temperature & Precipitation ( 500 years)","Label":"Temperature & Precipitation ( 500 years)","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Tree and plant type ( Observation )","Label":"Tree and plant type ( Observation )","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Phosporus Levels in Soil ","Label":"Phosporus Levels in Soil ","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Soil Erosion (10000 years)","Label":"Soil Erosion (10000 years)","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Forest Biomass ( 4000 years )","Label":"Forest Biomass ( 4000 years )","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Maps (Historical , Sattelite Images )","Label":"Maps (Historical , Sattelite Images )","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Oral Histories ( interviews)","Label":"Oral Histories ( interviews)","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Mapping (Actor and Institutional )","Label":"Mapping (Actor and Institutional )","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"State Registers","Label":"State Registers","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Meta-analysis of Sources","Label":"Meta-analysis of Sources","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Conceptual Maps","Label":"Conceptual Maps","group":"","level":3,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Local Narratives","Label":"Local Narratives","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Household Interviews","Label":"Household Interviews","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Sketches ( ethnographic )","Label":"Sketches ( ethnographic )","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Location of Water Sources","Label":"Location of Water Sources","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Written Regulations","Label":"Written Regulations","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Irrigation Channels","Label":"Irrigation Channels","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Household Surveys","Label":"Household Surveys","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Survey Photographs","Label":"Survey Photographs","group":"","level":null,"discipline":"hgeo","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Unevenly Grown bushes (Observation): grazing indicator","Label":"Unevenly Grown bushes (Observation): grazing indicator","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Degradation Indicators, tree types: Juniper","Label":"Degradation Indicators, tree types: Juniper","group":"","level":null,"discipline":"eco","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Worked Stone ( Observation )","Label":"Worked Stone ( Observation )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Pottery Sherds ( templates )","Label":"Pottery Sherds ( templates )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Human Bones","Label":"Human Bones","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Animal Bones","Label":"Animal Bones","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Graves ( Sites )","Label":"Graves ( Sites )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Architectural Notebooks ( operational: reconstruction, credibility )","Label":"Architectural Notebooks ( operational: reconstruction, credibility )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"C and O isotope analysis ( Dating )","Label":"C and O isotope analysis ( Dating )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Survey Notebooks ( operational: credibility )","Label":"Survey Notebooks ( operational: credibility )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Excavation Notebooks ( operational: credibility )","Label":"Excavation Notebooks ( operational: credibility )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Excavation Layer Photographs ( operational)","Label":"Excavation Layer Photographs ( operational)","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Pottery Sherds ( Illustrations )","Label":"Pottery Sherds ( Illustrations )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Pottery Sherds ( photographs )","Label":"Pottery Sherds ( photographs )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Landscape Characteristics (eg. viewshed, outpost, elevation )","Label":"Landscape Characteristics (eg. viewshed, outpost, elevation )","group":"","level":null,"discipline":"arch","Type":"data","pos_x":null,"pos_y":null,"oblig":""},
{"id":"Regulation","Label":"Regulation","group":"Politics and Governance","level":3,"discipline":"hgeo","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Revolution Disruption","Label":"Revolution Disruption","group":"Time","level":3,"discipline":"hgeo","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Climate Change","Label":"Climate Change","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Single Human Behaviour with Societal Impact","Label":"Single Human Behaviour with Societal Impact","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Random Events with Large Concequences","Label":"Random Events with Large Concequences","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Earthquake","Label":"Earthquake","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Stability","Label":"Stability","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Stability","Label":"Stability","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Opportunity","Label":"Opportunity","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Information Transmission","Label":"Information Transmission","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Inspiration Stimuli","Label":"Inspiration Stimuli","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Challenges","Label":"Challenges","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Iteration","Label":"Iteration","group":"Conceptual","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Evolution","Label":"Evolution","group":"Conceptual","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Attractor States","Label":"Attractor States","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Ideology","Label":"Ideology","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"},
{"id":"Sudden Change","Label":"Sudden Change","group":"Drivers","level":2,"discipline":"eco","Type":"event","pos_x":1,"pos_y":1,"oblig":"FALSE"}]